apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Flux Kustomizations with proper dependencies
  - infrastructure/core.yaml
  - infrastructure/storage.yaml
  - infrastructure/networking.yaml
  - infrastructure/apps.yaml