# Legacy BGP Configuration using CiliumBGPPeeringPolicy
# This approach might be more compatible with Cilium v1.17.6

apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    # Virtual router for bgp-default pool services
    - localASN: 64512
      exportPodCIDR: true
      serviceSelector:
        matchLabels:
          "io.cilium/lb-ipam-pool": "bgp-default"
      serviceAdvertisements:
        - LoadBalancerIP
      neighbors:
        - peerAddress: "172.29.51.1/32"
          peerASN: 64513
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
    # Virtual router for bgp-ingress pool services
    - localASN: 64512
      exportPodCIDR: false
      serviceSelector:
        matchLabels:
          "io.cilium/lb-ipam-pool": "bgp-ingress"
      serviceAdvertisements:
        - LoadBalancerIP
      neighbors:
        - peerAddress: "172.29.51.1/32"
          peerASN: 64513
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
    # Virtual router for bgp-reserved pool services
    - localASN: 64512
      exportPodCIDR: false
      serviceSelector:
        matchLabels:
          "io.cilium/lb-ipam-pool": "bgp-reserved"
      serviceAdvertisements:
        - LoadBalancerIP
      neighbors:
        - peerAddress: "172.29.51.1/32"
          peerASN: 64513
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
---
# BGP authentication secret (populated by External Secrets)
apiVersion: v1
kind: Secret
metadata:
  name: cilium-bgp-auth
  namespace: kube-system
type: Opaque
data:
  # BGP authentication password (base64 encoded)
  # This will be populated by External Secrets from 1Password
  password: ""
---
# External Secret for BGP authentication
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-bgp-auth
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: cilium-bgp-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "BGP Authentication - home-ops"
        property: "password"
