# Minimal BGP Configuration for Cilium v1.17.6
# Simplified to avoid schema validation errors

apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-loadbalancer-advertisements
  namespace: kube-system
spec:
  advertisements:
    # Announce LoadBalancer service IPs via BGP
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
          - ExternalIP
    # Announce Pod CIDR for internal routing
    - advertisementType: "PodCIDR"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-cluster
  namespace: kube-system
spec:
  bgpInstances:
    - name: "main-bgp-instance"
      localASN: 64512
      peers:
        - name: "unifi-udm-pro"
          peerASN: 64513
          peerAddress: "172.29.51.1"
          peerConfigRef:
            name: "cilium-bgp-peer-config"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-bgp-peer-config
  namespace: kube-system
spec:
  # Authentication secret for BGP peering
  authSecretRef: cilium-bgp-auth
  # Graceful restart configuration
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 120
---
# BGP authentication secret (populated by External Secrets)
apiVersion: v1
kind: Secret
metadata:
  name: cilium-bgp-auth
  namespace: kube-system
type: Opaque
data:
  # BGP authentication password (base64 encoded)
  # This will be populated by External Secrets from 1Password
  password: ""
---
# External Secret for BGP authentication
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-bgp-auth
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: cilium-bgp-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "BGP Authentication - home-ops"
        property: "password"