---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-automation
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: mqtt-broker
    app.kubernetes.io/part-of: home-automation-stack
data:
  mosquitto.conf: |
    # Minimal Mosquitto configuration to avoid port conflicts
    user mosquitto

    # Persistence
    persistence true
    persistence_location /mosquitto/data/

    # Logging
    log_dest stdout
    log_type error
    log_type warning
    log_type information

    # Authentication
    password_file /mosquitto/config/passwd

    # Network listeners - explicit only, no default listener
    listener 1883 0.0.0.0
    allow_anonymous false

    listener 9001 0.0.0.0
    protocol websockets
    allow_anonymous false

    # MQTT over TLS listener (port 8883) - disabled for now
    # listener 8883 0.0.0.0
    # protocol mqtt
    # cafile /mosquitto/certs/ca.crt
    # certfile /mosquitto/certs/server.crt
    # keyfile /mosquitto/certs/server.key
    # require_certificate false
    # use_identity_as_username false

    # =================================================================
    # Topic Access Control
    # =================================================================

    # Default ACL - authenticated users can access all topics
    # This can be restricted further based on specific requirements
    # acl_file disabled - using password-based authentication only

    # =================================================================
    # Performance Tuning
    # =================================================================

    # Memory limits
    memory_limit 0

    # Queue settings for IoT devices
    # max_queued_messages already defined above
    queue_qos0_messages false

    # Retain message settings
    # max_retained_messages removed - not supported in current Mosquitto version
    retained_persistence true

    # Client settings
    persistent_client_expiration 1m

    # =================================================================
    # Home Assistant Integration Settings
    # =================================================================

    # Optimize for Home Assistant MQTT discovery
    # These settings ensure reliable message delivery for HA

    # Keep alive settings
    max_keepalive 65535

    # Will message settings for device availability
    # (Home Assistant uses will messages for device tracking)

    # Bridge settings (if connecting to external MQTT brokers)
    # connection bridge-01
    # address external-mqtt-broker:1883
    # topic homeassistant/# out 1
    # topic homeassistant/# in 1

    # =================================================================
    # Monitoring and Health
    # =================================================================

    # System topic publishing for monitoring
    sys_interval 10

    # Client connection tracking - removed deprecated clientid_prefixes
    # clientid_prefixes

    # =================================================================
    # Additional Security Hardening
    # =================================================================

    # Disable certain features for security
    allow_zero_length_clientid true
    auto_id_prefix auto-

    # Connection limits per client
    # max_connections already defined above

    # Protocol version restrictions
    # protocol_version mqttv311

    # =================================================================
    # End of Configuration
    # =================================================================
