---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-credentials
  namespace: home-automation
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: mqtt-broker
    app.kubernetes.io/part-of: home-automation-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: mosquitto-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: mosquitto
          app.kubernetes.io/component: mqtt-broker
          app.kubernetes.io/part-of: home-automation-stack
      data:
        username: "{{ .mqtt_username }}"
        password: "{{ .mqtt_password }}"
  data:
    - secretKey: mqtt_username  # pragma: allowlist secret
      remoteRef:
        key: "Mosquitto MQTT Broker - home-ops"
        property: "username"
    - secretKey: mqtt_password  # pragma: allowlist secret
      remoteRef:
        key: "Mosquitto MQTT Broker - home-ops"
        property: "password"  # pragma: allowlist secret
