---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: home-automation
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: mqtt-broker
    app.kubernetes.io/part-of: home-automation-stack
    backup-tier: "important"
    backup-type: "mqtt-data"
    application: "mosquitto"
  annotations:
    backup.longhorn.io/volume-snapshot-class: "longhorn-snapshot-vsc"
    backup.longhorn.io/recurring-job-group: "mqtt-data"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 2Gi
