---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-automation
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: mqtt-broker
    app.kubernetes.io/part-of: home-automation-stack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: mqtt-broker
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    - name: mqtt-tls
      port: 8883
      targetPort: mqtt-tls
      protocol: TCP
    - name: websockets
      port: 9001
      targetPort: websockets
      protocol: TCP
---
# LoadBalancer service for external MQTT access if needed
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-external
  namespace: home-automation
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: mqtt-broker
    app.kubernetes.io/part-of: home-automation-stack
    io.cilium/lb-ipam-pool: "bgp-default"
  annotations:
    io.cilium/lb-ipam-pool: "bgp-default"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: mqtt-broker
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    - name: mqtt-tls
      port: 8883
      targetPort: mqtt-tls
      protocol: TCP
