apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h
  values:
    # Talos-specific configuration
    securityContext:
      privileged: true
    
    # CNI Configuration
    cni:
      install: true
      exclusive: false
    
    # IPAM Configuration
    ipam:
      mode: kubernetes
    
    # API Server Configuration
    k8sServiceHost: "172.29.51.10"
    k8sServicePort: 6443
    
    # Kube-proxy replacement - must be disabled in Talos
    kubeProxyReplacement: false
    
    # Enable Hubble for observability
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    
    # Operator configuration
    operator:
      replicas: 1
      rollOutPods: true
    
    # Node selector for control plane scheduling
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule