apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h
  values:
    # Talos-specific configuration
    securityContext:
      privileged: true
    
    # CNI Configuration
    cni:
      install: true
      exclusive: false
    
    # IPAM Configuration with IPv6 dual-stack support
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList: ["10.0.0.0/8"]
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv6PodCIDRList: ["fd00:10:244::/48"]
        clusterPoolIPv6MaskSize: 64
    
    # IPv6 dual-stack configuration
    ipv6:
      enabled: true
    
    # Enable dual-stack mode
    enableIPv4: true
    enableIPv6: true
    
    # API Server Configuration for Talos
    # Use the cluster VIP instead of localhost for pod access
    k8sServiceHost: 172.29.51.10
    k8sServicePort: 6443
    
    # Kube-proxy replacement - must be disabled in Talos
    kubeProxyReplacement: false
    
    # Enable Hubble for observability
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    
    # BGP Configuration
    bgpControlPlane:
      enabled: true
    
    # Load Balancer Configuration
    loadBalancer:
      algorithm: maglev
      mode: dsr
    
    # Enable L2 announcements for LoadBalancer IPAM
    l2announcements:
      enabled: true
    
    # Operator configuration
    operator:
      replicas: 1
      rollOutPods: true
    
    # Node selector for control plane scheduling
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoSchedule