apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Cilium core CNI is deployed via Bootstrap (task apps:deploy-cilium)
  # Only operational features are managed via GitOps
  - loadbalancer-pool.yaml
  - loadbalancer-pool-ipv6.yaml
  # ingress-hubble.yaml removed - using authentik proxy instead of native ingress