apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Cilium deployed via GitOps (Flux HelmRelease)
  - namespace.yaml
  - helmrelease.yaml
  - loadbalancer-pool.yaml
  - loadbalancer-pool-ipv6.yaml