apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cilium core CNI is deployed via Bootstrap (task apps:deploy-cilium)
# LoadBalancer IP pools moved to infrastructure/cilium-pools (Phase 1)
# Only remaining operational features are managed via GitOps here
# ingress-hubble.yaml removed - using authentik proxy instead of native ingress

resources: []
