apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
  namespace: kube-system
spec:
  blocks:
    - start: "172.29.51.100"
      stop: "172.29.51.199"
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-pool: "default"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress
  namespace: kube-system
spec:
  blocks:
    - start: "172.29.51.200"
      stop: "172.29.51.220"
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-pool: "ingress"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
  namespace: kube-system
spec:
  loadBalancerIPs: true
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  interfaces:
    - "enp3s0f0"