---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-ingress-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-cert-manager
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-onepassword
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-dns
      namespace: external-dns-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cloudflare-tunnel
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/cloudflare-tunnel
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-onepassword
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cloudflare-tunnel
      namespace: cloudflare-tunnel