apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi-secret
  namespace: external-dns-internal-system
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: external-dns-unifi-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-key: "{{ .unifi_api_key }}"
  data:
  - secretKey: unifi_api_key
    remoteRef:
      key: "Home-ops Unifi API"
      property: password