apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns-internal-system

resources:
  - namespace.yaml
  - external-secret.yaml
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/part-of: external-dns-internal
  app.kubernetes.io/managed-by: flux

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: external-dns-internal
