apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-admin-token-enhanced
  namespace: headlamp
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-admin-token-enhanced
    creationPolicy: Owner
  data:
    - secretKey: token # pragma: allowlist secret
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: token
