apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
  namespace: headlamp
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: SecretStore
  target:
    name: headlamp-oidc
    creationPolicy: Owner
  data:
    - secretKey: clientId # pragma: allowlist secret
      remoteRef:
        key: headlamp-oidc
        property: client_id
    - secretKey: clientSecret # pragma: allowlist secret
      remoteRef:
        key: headlamp-oidc
        property: client_secret # pragma: allowlist secret
---
# Temporary manual secret for initial setup
# Replace these values after creating the Authentik application
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc-manual
  namespace: headlamp
type: Opaque
stringData:
  clientId: "headlamp"
  clientSecret: "REPLACE_WITH_AUTHENTIK_CLIENT_SECRET" # pragma: allowlist secret
