apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headlamp
resources:
  - namespace.yaml
  - helmrepository.yaml
  - headlamp-oidc-secret.yaml
  - helmrelease.yaml
  - rbac.yaml
