[tools]
# renovate: datasource=github-releases depName=kubernetes/kubernetes
kubectl = "1.31.1"
# renovate: datasource=github-releases depName=siderolabs/talos
talosctl = "1.8.1"
# renovate: datasource=github-releases depName=fluxcd/flux2
flux = "2.4.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
kustomize = "5.4.3"
# renovate: datasource=github-releases depName=helm/helm
helm = "3.16.1"
# renovate: datasource=github-releases depName=cilium/cilium-cli
cilium = "0.16.16"
# renovate: datasource=github-releases depName=mikefarah/yq
yq = "4.44.3"
# renovate: datasource=github-releases depName=jqlang/jq
jq = "1.7.1"
# renovate: datasource=github-releases depName=go-task/task
go-task = "3.38.0"