apiVersion: v1
kind: Pod
metadata:
  name: network-test
  namespace: authentik-proxy
spec:
  containers:
    - name: test
      image: nicolaka/netshoot
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 3600; done"]
  restartPolicy: Never
