apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-usb-ssd-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-usb-ssd-pod
  namespace: default
spec:
  containers:
    - name: test-container
      image: busybox:1.35
      command: ["/bin/sh"]
      args:
        ["-c", "while true; do echo $(date) >> /data/test.log; sleep 30; done"]
      volumeMounts:
        - name: test-storage
          mountPath: /data
  volumes:
    - name: test-storage
      persistentVolumeClaim:
        claimName: test-usb-ssd-pvc
  restartPolicy: Always
