---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: matter-server
  namespace: home-automation

resources:
  - helmrelease.yaml

labels:
  - pairs:
      app.kubernetes.io/name: matter-server
      app.kubernetes.io/component: matter-server
      app.kubernetes.io/part-of: home-automation-stack

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: matter-server
    app.kubernetes.io/component: matter-server
    app.kubernetes.io/part-of: home-automation-stack
  annotations:
    config.kubernetes.io/local-config: "true"
