apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # namespace.yaml is already created by infrastructure/monitoring
  # grafana.yaml removed - using authentik proxy instead of native ingress
  []