apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.3.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  values:
    alertmanager:
      enabled: true
      service:
        type: LoadBalancer
        loadBalancerIP: "172.29.51.160"
        annotations:
          io.cilium/lb-ipam-pool: "default"

    prometheus:
      service:
        type: LoadBalancer
        loadBalancerIP: "172.29.51.161"
        annotations:
          io.cilium/lb-ipam-pool: "default"

      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi

        nodeSelector:
          kubernetes.io/os: linux

        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule

    grafana:
      service:
        type: LoadBalancer
        loadBalancerIP: "172.29.51.162"
        annotations:
          io.cilium/lb-ipam-pool: "default"

      persistence:
        enabled: true
        storageClassName: longhorn
        size: 10Gi

      nodeSelector:
        kubernetes.io/os: linux

      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
