apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://longhorn-backups-home-ops@us-west-2/"
  credentialSecret: "longhorn-s3-backup-credentials"
  pollInterval: 5m0s
