apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-s3-backup-credentials
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: longhorn-s3-backup-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "AWS Access Key - longhorn-s3-backup - home-ops"
        property: "access key id"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "AWS Access Key - longhorn-s3-backup - home-ops"
        property: "secret access key"