apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrelease.yaml
  - storage-class.yaml
  # - volume-snapshot-class.yaml  # Commented out until Longhorn CRDs are installed
  - ingress.yaml