apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrelease.yaml
  - storage-class.yaml
  # volume-snapshot-class.yaml requires CRDs from Longhorn CSI driver - apply after Longhorn is deployed
  - ingress.yaml