apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrelease.yaml
  - storage-class.yaml
  - volume-snapshot-class.yaml
  - ingress.yaml
  - external-secret-s3.yaml
  - backup-target-patch.yaml
  - recurring-jobs.yaml
  - volume-snapshots-critical.yaml
  - backup-monitoring.yaml
  - backup-restore-procedures.yaml
  - database-backup-examples.yaml