# Longhorn RecurringJobs for automated backup strategy
# Homelab-optimized with database support and 24-hour RPO
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: monitoring-daily-snapshot
  namespace: longhorn-system
spec:
  cron: "0 2 * * *" # Daily at 2 AM
  task: "snapshot"
  groups:
    - monitoring
  retain: 7 # Keep 7 daily snapshots
  concurrency: 2
  labels:
    backup-tier: "critical"
    backup-type: "snapshot"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: monitoring-weekly-backup
  namespace: longhorn-system
spec:
  cron: "0 3 * * 0" # Weekly on Sunday at 3 AM
  task: "backup"
  groups:
    - monitoring
  retain: 4 # Keep 4 weekly backups (1 month)
  concurrency: 1
  labels:
    backup-tier: "critical"
    backup-type: "s3-backup"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: database-daily-snapshot
  namespace: longhorn-system
spec:
  cron: "0 1 * * *" # Daily at 1 AM (before monitoring)
  task: "snapshot"
  groups:
    - database
  retain: 7 # Keep 7 daily snapshots
  concurrency: 1 # Databases need sequential processing
  labels:
    backup-tier: "critical"
    backup-type: "snapshot"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: database-weekly-backup
  namespace: longhorn-system
spec:
  cron: "0 4 * * 0" # Weekly on Sunday at 4 AM
  task: "backup"
  groups:
    - database
  retain: 8 # Keep 8 weekly backups (2 months for databases)
  concurrency: 1
  labels:
    backup-tier: "critical"
    backup-type: "s3-backup"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: application-weekly-snapshot
  namespace: longhorn-system
spec:
  cron: "0 5 * * 0" # Weekly on Sunday at 5 AM
  task: "snapshot"
  groups:
    - application
  retain: 4 # Keep 4 weekly snapshots
  concurrency: 2
  labels:
    backup-tier: "important"
    backup-type: "snapshot"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: application-monthly-backup
  namespace: longhorn-system
spec:
  cron: "0 6 1 * *" # Monthly on 1st at 6 AM
  task: "backup"
  groups:
    - application
  retain: 3 # Keep 3 monthly backups
  concurrency: 1
  labels:
    backup-tier: "important"
    backup-type: "s3-backup"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: cleanup-old-snapshots
  namespace: longhorn-system
spec:
  cron: "0 7 * * 0" # Weekly cleanup on Sunday at 7 AM
  task: "snapshot-cleanup"
  groups:
    - monitoring
    - database
    - application
  retain: 0 # This job cleans up, doesn't retain
  concurrency: 1
  labels:
    backup-tier: "maintenance"
    backup-type: "cleanup"
