apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-unifi-webhook
  namespace: external-dns-unifi-system
  labels:
    app.kubernetes.io/name: external-dns-unifi-webhook
    app.kubernetes.io/component: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns-unifi-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns-unifi-webhook
    spec:
      serviceAccountName: external-dns-unifi-webhook
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: webhook
          image: ghcr.io/kashalls/external-dns-unifi-webhook:v0.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-webhook
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          env:
            - name: UNIFI_HOST
              value: "https://192.168.1.1" # Update with your UDM IP
            - name: UNIFI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-dns-unifi-secret
                  key: api-key
            - name: UNIFI_PORT
              value: "443"
            - name: UNIFI_VERSION
              value: "unifiOS"
            - name: LOG_LEVEL
              value: "info"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8888"
            - name: SERVER_READ_TIMEOUT
              value: "60s"
            - name: SERVER_WRITE_TIMEOUT
              value: "60s"
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 25Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: external-dns-unifi-webhook
  namespace: external-dns-unifi-system
  labels:
    app.kubernetes.io/name: external-dns-unifi-webhook
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 8888
      targetPort: http-webhook
      protocol: TCP
      name: http-webhook
  selector:
    app.kubernetes.io/name: external-dns-unifi-webhook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-unifi-webhook
  namespace: external-dns-unifi-system
  labels:
    app.kubernetes.io/name: external-dns-unifi-webhook
