apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: external-dns-unifi-system

resources:
  - namespace.yaml
  - deployment.yaml
  - external-secret.yaml

commonLabels:
  app.kubernetes.io/part-of: external-dns-unifi
  app.kubernetes.io/managed-by: flux

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: external-dns-unifi-webhook
