apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.19.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true

    replicaCount: 1

    serviceAccount:
      create: true
      name: external-secrets

    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534

    resources:
      limits:
        memory: 256Mi
        cpu: 200m
      requests:
        memory: 128Mi
        cpu: 100m

    nodeSelector:
      kubernetes.io/os: linux

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

    env:
      - name: GOMAXPROCS
        value: "2"

    webhook:
      create: true
      port: 9443
      timeoutSeconds: 30
      failurePolicy: Ignore

    # Configure webhook validation timeouts
    validatingWebhookConfiguration:
      timeoutSeconds: 30

    certController:
      create: true

    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  labels:
    name: external-secrets-system
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
