apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg-barman-plugin
  namespace: cnpg-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/barman-cloud-plugin