apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-barman-plugin
  namespace: cnpg-system
spec:
  interval: 30m
  chart:
    spec:
      chart: barman-cloud
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg-barman-plugin
        namespace: cnpg-system
      interval: 12h
  values:
    # Plugin configuration for Barman Cloud
    image:
      repository: ghcr.io/cloudnative-pg/barman-cloud
      tag: "1.26.1"
      pullPolicy: IfNotPresent

    # Resources for the plugin
    resources:
      requests:
        memory: "64Mi"
        cpu: "10m"
      limits:
        memory: "128Mi"
        cpu: "100m"

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
      runAsGroup: 999
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

    # Node selector for all nodes
    nodeSelector: {}

    # Tolerations for scheduling
    tolerations: []

    # Affinity rules
    affinity: {}
