apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cnpg-barman-plugin
  namespace: cnpg-system

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml