apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cnpg-barman-plugin
  namespace: cnpg-system

resources:
  - namespace.yaml
  - https://github.com/cloudnative-pg/barman-cloud/releases/download/v0.5.0/barman-cloud.yaml

commonLabels:
  app.kubernetes.io/name: cnpg-barman-plugin
  app.kubernetes.io/component: database-plugin
  app.kubernetes.io/part-of: cnpg-system
