---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-secrets
  namespace: home-automation
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/component: home-automation-core
    app.kubernetes.io/part-of: home-automation-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: home-assistant-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: home-assistant
          app.kubernetes.io/component: home-automation-core
          app.kubernetes.io/part-of: home-automation-stack
      data:
        # MQTT credentials
        mqtt_username: "{{ .mqtt_username }}"
        mqtt_password: "{{ .mqtt_password }}"

        # Home Assistant secrets
        home_latitude: "{{ .home_latitude }}"
        home_longitude: "{{ .home_longitude }}"
        home_elevation: "{{ .home_elevation }}"

        # API keys and tokens
        weather_api_key: "{{ .weather_api_key }}"
        google_api_key: "{{ .google_api_key }}"

        # Security keys
        secret_key: "{{ .secret_key }}"

        # Database URL (constructed from database credentials)
        postgres_db_url: "postgresql://{{ .db_username }}:{{ .db_password }}@homeassistant-postgresql-rw.home-automation.svc.cluster.local:5432/homeassistant"
  data:
    # MQTT credentials (shared with Mosquitto)
    - secretKey: mqtt_username
      remoteRef:
        key: "Mosquitto MQTT Broker - home-ops"
        property: "username"
    - secretKey: mqtt_password
      remoteRef:
        key: "Mosquitto MQTT Broker - home-ops"
        property: "password"

    # Home location data
    - secretKey: home_latitude
      remoteRef:
        key: "Home Assistant - home-ops"
        property: "home_latitude"
    - secretKey: home_longitude
      remoteRef:
        key: "Home Assistant - home-ops"
        property: "home_longitude"
    - secretKey: home_elevation
      remoteRef:
        key: "Home Assistant - home-ops"
        property: "home_elevation"

    # API keys
    - secretKey: weather_api_key
      remoteRef:
        key: "Home Assistant - home-ops"
        property: "weather_api_key"
    - secretKey: google_api_key
      remoteRef:
        key: "Home Assistant - home-ops"
        property: "google_api_key"

    # Security
    - secretKey: secret_key
      remoteRef:
        key: "Home Assistant - home-ops"
        property: "secret_key"

    # Database credentials (from existing database secret)
    - secretKey: db_username
      remoteRef:
        key: "Home Assistant Database - home-ops"
        property: "username"
    - secretKey: db_password
      remoteRef:
        key: "Home Assistant Database - home-ops"
        property: "password"
