---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: home-assistant
  namespace: home-automation

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml
  - external-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/component: home-automation-core
      app.kubernetes.io/part-of: home-automation-stack

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/component: home-automation-core
