---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-superuser-credentials
  namespace: home-automation
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/component: home-automation-core
    app.kubernetes.io/part-of: home-automation-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: postgresql-superuser-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: home-assistant
          app.kubernetes.io/component: database
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: "PostgreSQL Superuser - home-ops"
        property: "username"
    - secretKey: password
      remoteRef:
        key: "PostgreSQL Superuser - home-ops"
        property: "password"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-database-credentials
  namespace: home-automation
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/component: home-automation-core
    app.kubernetes.io/part-of: home-automation-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: homeassistant-database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: home-assistant
          app.kubernetes.io/component: database
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        database: "homeassistant"
        host: "postgresql-cluster-rw.postgresql-system.svc.cluster.local"
        port: "5432"
  data:
    - secretKey: username
      remoteRef:
        key: "Home Assistant Database - home-ops"
        property: "username"
    - secretKey: password
      remoteRef:
        key: "Home Assistant Database - home-ops"
        property: "password"