apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: home-ops-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    
    ingress:
      # Grafana - monitoring dashboard (public access)
      - hostname: grafana.geoffdavis.com
        service: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
        
      # Prometheus - metrics collection (public access)
      - hostname: prometheus.k8s.geoffdavis.com
        service: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        
      # Longhorn - storage management (public access, secured with basic auth)
      - hostname: longhorn.k8s.geoffdavis.com
        service: http://longhorn-frontend.longhorn-system.svc.cluster.local:80
        
      # Kubernetes Dashboard (public access, secured)
      - hostname: dashboard.k8s.geoffdavis.com
        service: http://kubernetes-dashboard-web.kubernetes-dashboard.svc.cluster.local:8000
        
      # AlertManager - alert management (public access)
      - hostname: alertmanager.k8s.geoffdavis.com
        service: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
        
      # Hubble UI - network observability (public access)
      - hostname: hubble.k8s.geoffdavis.com
        service: http://hubble-ui.cilium-system.svc.cluster.local:80
        
      # Default rule - catch all
      - service: http_status:404