apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: "Cloudflare Tunnel Credentials"
        property: "credentials.json"
    - secretKey: tunnel-token
      remoteRef:
        key: "Cloudflare Tunnel Credentials"
        property: "tunnel-token"