apiVersion: v1
kind: Namespace
metadata:
  name: volume-snapshot-system
  labels:
    name: volume-snapshot-system
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted