apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-superuser-credentials
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: database-init
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: postgresql-superuser-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: "PostgreSQL Superuser - home-ops"
        property: "username"
    - secretKey: password
      remoteRef:
        key: "PostgreSQL Superuser - home-ops"
        property: "password"