---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-admin-api-token
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: identity-provider
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-admin-api-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        token: "{{ .token }}"
        AUTHENTIK_BOOTSTRAP__TOKEN: "{{ .token }}"
        created: "{{ .created }}"
        expires: "{{ .expires }}"
        description: "{{ .description }}"
  data:
    - secretKey: token
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: token
    - secretKey: created
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: created
    - secretKey: expires
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: expires
    - secretKey: description
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: description
  refreshInterval: 5m