apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-radius-token
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: radius
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-radius-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: "Authentik RADIUS Token - home-ops"
        property: "password"