---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-admin-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: SecretStore
  target:
    name: authentik-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: authentik-admin-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: authentik-admin-credentials
        property: password
    - secretKey: email
      remoteRef:
        key: authentik-admin-credentials
        property: email