apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-config
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: identity-provider
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-config
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: authentik
          app.kubernetes.io/component: identity-provider
      data:
        AUTHENTIK_SECRET_KEY: "{{ .secret_key }}"
        AUTHENTIK_EMAIL__HOST: "{{ .smtp_host }}"
        AUTHENTIK_EMAIL__PORT: "{{ .smtp_port }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .smtp_username }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .smtp_password }}"
        AUTHENTIK_EMAIL__USE_TLS: "{{ .smtp_use_tls }}"
        AUTHENTIK_EMAIL__FROM: "{{ .smtp_from }}"
        RADIUS_SHARED_SECRET: "{{ .radius_shared_secret }}"
  data:
    - secretKey: secret_key
      remoteRef:
        key: "Authentik Secret Key - home-ops"
        property: "password"
    - secretKey: smtp_host
      remoteRef:
        key: "Authentik Configuration - home-ops"
        property: "smtp_host"
    - secretKey: smtp_port
      remoteRef:
        key: "Authentik Configuration - home-ops"
        property: "smtp_port"
    - secretKey: smtp_username
      remoteRef:
        key: "Authentik Configuration - home-ops"
        property: "smtp_username"
    - secretKey: smtp_password
      remoteRef:
        key: "Authentik Configuration - home-ops"
        property: "smtp_password"
    - secretKey: smtp_use_tls
      remoteRef:
        key: "Authentik Configuration - home-ops"
        property: "smtp_use_tls"
    - secretKey: smtp_from
      remoteRef:
        key: "Authentik Configuration - home-ops"
        property: "smtp_from"
    - secretKey: radius_shared_secret
      remoteRef:
        key: "Authentik RADIUS Shared Secret - home-ops"
        property: "password"