apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-database-credentials
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: identity-provider
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: authentik
          app.kubernetes.io/component: identity-provider
      data:
        AUTHENTIK_POSTGRESQL__HOST: "postgresql-cluster-rw.postgresql-system.svc.cluster.local"
        AUTHENTIK_POSTGRESQL__NAME: "authentik"
        AUTHENTIK_POSTGRESQL__USER: "{{ .username }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .password }}"
        AUTHENTIK_POSTGRESQL__PORT: "5432"
        AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: "false"
        AUTHENTIK_POSTGRESQL__SSLMODE: "require"
  data:
    - secretKey: username
      remoteRef:
        key: "PostgreSQL Authentik User - home-ops"
        property: "username"
    - secretKey: password
      remoteRef:
        key: "PostgreSQL Authentik User - home-ops"
        property: "password"
