---
# 1PASSWORD DUPLICATES RESOLVED
# The duplicate "Authentik Outpost Token - home-ops" entries have been cleaned up
# Reverted to original configuration using the correct outpost token
#
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-admin-token-enhanced
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: token-management
    app.kubernetes.io/part-of: authentik
  annotations:
    external-secrets.io/refresh-interval: "5m"
    token-management.authentik.io/rotation-enabled: "true"
    token-management.authentik.io/overlap-days: "30"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-radius-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: authentik
          app.kubernetes.io/component: token-management
          app.kubernetes.io/part-of: authentik
        annotations:
          token-management.authentik.io/last-rotation: "{{ .last_rotation | default \"never\" }}"
          token-management.authentik.io/expires: "{{ .expires | default \"unknown\" }}"
          token-management.authentik.io/created: "{{ .created | default \"unknown\" }}"
          token-management.authentik.io/description: "{{ .description | default \"Authentik API Token\" }}"
          token-management.authentik.io/rotation-status: "{{ .rotation_status | default \"active\" }}"
      data:
        # Primary token (active)
        token: "{{ .token }}"
        
        # Token metadata for rotation management
        expires: "{{ .expires | default \"\" }}"
        created: "{{ .created | default \"\" }}"
        description: "{{ .description | default \"\" }}"
        last_rotation: "{{ .last_rotation | default \"\" }}"
        rotation_status: "{{ .rotation_status | default \"active\" }}"
        
        # Secondary token fields (for rotation overlap - initially empty)
        token_secondary: "{{ .token_secondary | default \"\" }}"
        expires_secondary: "{{ .expires_secondary | default \"\" }}"
        created_secondary: "{{ .created_secondary | default \"\" }}"
        
        # Token validation endpoint for health checks
        validation_endpoint: "http://authentik-server.authentik.svc.cluster.local/api/v3/core/users/me/"
  data:
    - secretKey: token
      remoteRef:
        key: "Authentik Outpost Token - home-ops"
        property: "token"
    - secretKey: expires
      remoteRef:
        key: "Authentik Outpost Token - home-ops"
        property: "expires"
    - secretKey: created
      remoteRef:
        key: "Authentik Outpost Token - home-ops"
        property: "created"
    - secretKey: description
      remoteRef:
        key: "Authentik Outpost Token - home-ops"
        property: "description"
    - secretKey: last_rotation
      remoteRef:
        key: "Authentik Outpost Token - home-ops"
        property: "last_rotation"
    - secretKey: rotation_status
      remoteRef:
        key: "Authentik Outpost Token - home-ops"
        property: "rotation_status"
    - secretKey: token_secondary
      remoteRef:
        key: "Authentik Outpost Token - home-ops"
        property: "token_secondary"
    - secretKey: expires_secondary
      remoteRef:
        key: "Authentik Outpost Token - home-ops"
        property: "expires_secondary"
    - secretKey: created_secondary
      remoteRef:
        key: "Authentik Outpost Token - home-ops"
        property: "created_secondary"
# Note: Token rotation configuration has been moved to ConfigMap
# See infrastructure/authentik/token-rotation-configmap.yaml