---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onepassword-connect-token
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: SecretStore
  target:
    name: onepassword-connect-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: 1Password Connect Credentials
        property: token