---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-admin-user
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: identity-provider
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-admin-user
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        email: "{{ .email }}"
        url: "{{ .url }}"
        created: "{{ .created }}"
  data:
    - secretKey: username
      remoteRef:
        key: "Authentik Admin User - home-ops"
        property: username
    - secretKey: password
      remoteRef:
        key: "Authentik Admin User - home-ops"
        property: password
    - secretKey: email
      remoteRef:
        key: "Authentik Admin User - home-ops"
        property: email
    - secretKey: url
      remoteRef:
        key: "Authentik Admin User - home-ops"
        property: url
    - secretKey: created
      remoteRef:
        key: "Authentik Admin User - home-ops"
        property: created
  refreshInterval: 5m
