---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-admin-token
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: admin-token
    app.kubernetes.io/part-of: authentik
  annotations:
    external-secrets.io/refresh-interval: "5m"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-admin-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: authentik
          app.kubernetes.io/component: admin-token
          app.kubernetes.io/part-of: authentik
        annotations:
          token-management.authentik.io/purpose: "admin-api"
          token-management.authentik.io/created: "{{ .created | default \"unknown\" }}"
          token-management.authentik.io/expires: "{{ .expires | default \"never\" }}"
      data:
        # Admin API token for authentik server internal operations
        token: "{{ .token }}"
        
        # Environment variable for authentik bootstrap token
        AUTHENTIK_BOOTSTRAP__TOKEN: "{{ .token }}"
        
        # Token metadata
        created: "{{ .created | default \"\" }}"
        expires: "{{ .expires | default \"\" }}"
        description: "{{ .description | default \"Authentik Admin API Token\" }}"
  data:
    - secretKey: token
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: "token"
    - secretKey: created
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: "created"
    - secretKey: expires
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: "expires"
    - secretKey: description
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: "description"