apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: authentik-bootstrap
  namespace: authentik

resources:
  # Core namespace and RBAC
  - namespace.yaml
  - service-account.yaml
  
  # Storage
  - pvc-media.yaml
  
  # External secrets for configuration and database
  - external-secret-config.yaml
  - external-secret-db.yaml
  - external-secret-postgresql-superuser.yaml
  - external-secret-admin-credentials.yaml
  
  # 1Password connect token for admin setup jobs
  - external-secret-onepassword-token.yaml
  
  # Bootstrap HelmRelease (no admin token dependencies)
  - bootstrap-helmrelease.yaml
  
  # Admin user and API token setup jobs
  - admin-user-job.yaml
  - admin-api-token-setup-job.yaml

commonLabels:
  app.kubernetes.io/name: authentik
  app.kubernetes.io/part-of: identity-provider
  app.kubernetes.io/component: bootstrap

images:
  - name: ghcr.io/goauthentik/server
    newTag: "2024.8.3"

secretGenerator:
  - name: authentik-bootstrap
    literals:
      - bootstrap-password=bootstrap-admin-password-temp
      - bootstrap-token=bootstrap-token-for-initial-setup-only
    options:
      disableNameSuffixHash: true

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: bootstrap
  annotations:
    config.kubernetes.io/local-config: "true"