apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: authentik-operational
  namespace: authentik

resources:
  # Core namespace and RBAC
  - namespace.yaml
  - service-account.yaml
  
  # Storage
  - pvc-media.yaml
  
  # External secrets for configuration and database
  - external-secret-config.yaml
  - external-secret-db.yaml
  - external-secret-postgresql-superuser.yaml
  - external-secret-admin-credentials.yaml
  
  # Enhanced token management for outpost authentication
  - external-secret-admin-token-enhanced.yaml
  
  # Main authentik ingress (now that we have tokens)
  - ingress.yaml
  
  # Operational HelmRelease (with external secrets)
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/name: authentik
  app.kubernetes.io/part-of: identity-provider
  app.kubernetes.io/component: operational

images:
  - name: ghcr.io/goauthentik/server
    newTag: "2024.8.3"

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: operational
  annotations:
    config.kubernetes.io/local-config: "true"