apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    name: authentik
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: identity-provider
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted