---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-token-rotation-config
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-token-rotation
    app.kubernetes.io/component: token-management
    app.kubernetes.io/part-of: authentik
data:
  # Rotation configuration
  rotation_enabled: "true"
  overlap_days: "30"
  check_interval: "24h"
  warning_days: "60"
  
  # 1Password configuration
  onepassword_vault: "Automation"
  onepassword_item: "Authentik Outpost Token - home-ops"
  
  # Notification configuration
  notification_enabled: "false"
  notification_webhook: ""
  
  # Token validation configuration
  validation_enabled: "true"
  validation_timeout: "30s"