---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: authentik-token-rotation
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-token-rotation
    app.kubernetes.io/component: token-management
    app.kubernetes.io/part-of: authentik
  annotations:
    flux.weave.works/automated: "false"
spec:
  # Run daily at 2 AM UTC
  schedule: "0 2 * * *"
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 300
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: authentik-token-rotation
        app.kubernetes.io/component: token-management
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 1800  # 30 minutes
      template:
        metadata:
          labels:
            app.kubernetes.io/name: authentik-token-rotation
            app.kubernetes.io/component: token-management
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
          serviceAccountName: authentik-token-rotation
          containers:
            - name: token-rotation
              image: python:3.12-slim
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 65534
                runAsGroup: 65534
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
                readOnlyRootFilesystem: true
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: ROTATION_ENABLED
                  valueFrom:
                    secretKeyRef:
                      name: authentik-token-rotation-config
                      key: rotation_enabled
                      optional: true
                - name: OVERLAP_DAYS
                  valueFrom:
                    secretKeyRef:
                      name: authentik-token-rotation-config
                      key: overlap_days
                      optional: true
                - name: WARNING_DAYS
                  valueFrom:
                    secretKeyRef:
                      name: authentik-token-rotation-config
                      key: warning_days
                      optional: true
                - name: VALIDATION_ENABLED
                  valueFrom:
                    secretKeyRef:
                      name: authentik-token-rotation-config
                      key: validation_enabled
                      optional: true
                - name: NOTIFICATION_ENABLED
                  valueFrom:
                    secretKeyRef:
                      name: authentik-token-rotation-config
                      key: notification_enabled
                      optional: true
                - name: NOTIFICATION_WEBHOOK
                  valueFrom:
                    secretKeyRef:
                      name: authentik-token-rotation-config
                      key: notification_webhook
                      optional: true
              volumeMounts:
                - name: token-manager-script
                  mountPath: /app
                  readOnly: true
                - name: tmp
                  mountPath: /tmp
                - name: pip-cache
                  mountPath: /home/nobody/.local
              workingDir: /app
              command:
                - /bin/bash
                - -c
                - |
                  set -euo pipefail
                  
                  echo "=== Authentik Token Rotation Job ==="
                  echo "Starting token rotation check at $(date -u)"
                  
                  # Install dependencies to writable volume
                  pip install --target /home/nobody/.local/lib/python3.12/site-packages requests pyyaml
                  export PYTHONPATH="/home/nobody/.local/lib/python3.12/site-packages:$PYTHONPATH"
                  
                  # Set Python path
                  export PYTHONPATH="/app:$PYTHONPATH"
                  
                  # Check if rotation is enabled
                  if [[ "${ROTATION_ENABLED:-true}" != "true" ]]; then
                    echo "Token rotation is disabled, skipping..."
                    exit 0
                  fi
                  
                  # Run token rotation check
                  echo "Checking token expiry status..."
                  python /app/authentik_token_manager.py list --json > /tmp/token_status.json
                  
                  # Parse token status and determine if rotation is needed
                  python -c "
                  import json
                  import sys
                  from datetime import datetime
                  
                  overlap_days = int('${OVERLAP_DAYS:-30}')
                  warning_days = int('${WARNING_DAYS:-60}')
                  
                  with open('/tmp/token_status.json', 'r') as f:
                      tokens = json.load(f)
                  
                  rotation_needed = False
                  warning_needed = False
                  
                  for token in tokens:
                      if token.get('days_remaining'):
                          days = token['days_remaining']
                          if days <= overlap_days:
                              print(f'Token {token[\"key\"]} expires in {days} days - rotation needed')
                              rotation_needed = True
                          elif days <= warning_days:
                              print(f'Token {token[\"key\"]} expires in {days} days - warning')
                              warning_needed = True
                  
                  if rotation_needed:
                      print('ROTATION_NEEDED=true')
                      sys.exit(10)  # Special exit code for rotation needed
                  elif warning_needed:
                      print('WARNING_NEEDED=true')
                      sys.exit(20)  # Special exit code for warning
                  else:
                      print('No action needed')
                      sys.exit(0)
                  " || rotation_status=$?
                  
                  case $rotation_status in
                    10)
                      echo "Token rotation is needed, starting rotation process..."
                      python /app/authentik_token_manager.py rotate --overlap-days ${OVERLAP_DAYS:-30}
                      if [[ $? -eq 0 ]]; then
                        echo "Token rotation completed successfully"
                        if [[ "${NOTIFICATION_ENABLED:-true}" == "true" && -n "${NOTIFICATION_WEBHOOK:-}" ]]; then
                          curl -X POST "${NOTIFICATION_WEBHOOK}" \
                            -H "Content-Type: application/json" \
                            -d '{"text":"✅ Authentik token rotation completed successfully","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' || true
                        fi
                      else
                        echo "Token rotation failed"
                        if [[ "${NOTIFICATION_ENABLED:-true}" == "true" && -n "${NOTIFICATION_WEBHOOK:-}" ]]; then
                          curl -X POST "${NOTIFICATION_WEBHOOK}" \
                            -H "Content-Type: application/json" \
                            -d '{"text":"❌ Authentik token rotation failed","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' || true
                        fi
                        exit 1
                      fi
                      ;;
                    20)
                      echo "Token expiry warning - no rotation needed yet"
                      if [[ "${NOTIFICATION_ENABLED:-true}" == "true" && -n "${NOTIFICATION_WEBHOOK:-}" ]]; then
                        curl -X POST "${NOTIFICATION_WEBHOOK}" \
                          -H "Content-Type: application/json" \
                          -d '{"text":"⚠️ Authentik token will expire soon","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' || true
                      fi
                      ;;
                    0)
                      echo "All tokens are healthy"
                      ;;
                    *)
                      echo "Unexpected status check result: $rotation_status"
                      exit 1
                      ;;
                  esac
                  
                  echo "Token rotation job completed at $(date -u)"
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "256Mi"
                  cpu: "200m"
          volumes:
            - name: token-manager-script
              configMap:
                name: authentik-token-manager-script
                defaultMode: 0755
            - name: tmp
              emptyDir: {}
            - name: pip-cache
              emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik-token-rotation
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-token-rotation
    app.kubernetes.io/component: token-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authentik-token-rotation
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-token-rotation
    app.kubernetes.io/component: token-management
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-token-rotation
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-token-rotation
    app.kubernetes.io/component: token-management
subjects:
  - kind: ServiceAccount
    name: authentik-token-rotation
    namespace: authentik
roleRef:
  kind: Role
  name: authentik-token-rotation
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-token-manager-script
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-token-rotation
    app.kubernetes.io/component: token-management
data:
  authentik_token_manager.py: |
    #!/bin/bash
    # Simple wrapper to run the actual Python script
    # The real script is in scripts/token-management/authentik_token_manager.py
    # For now, we'll create a simple version that updates 1Password with the current token
    
    set -euo pipefail
    
    echo "=== Authentik Token Manager ==="
    
    if [[ "$1" == "rotate" ]]; then
        echo "Starting token rotation process..."
        
        # Get the current token from the enhanced token setup job
        echo "Getting current token from enhanced token setup job..."
        JOB_NAME=$(kubectl get jobs -n authentik -l app.kubernetes.io/name=authentik-enhanced-token-setup --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[-1].metadata.name}' 2>/dev/null || echo "")
        
        if [[ -z "$JOB_NAME" ]]; then
            echo "ERROR: No enhanced token setup job found"
            exit 1
        fi
        
        echo "Found job: $JOB_NAME"
        
        # Extract token from job logs
        TOKEN=$(kubectl logs job/$JOB_NAME -n authentik 2>/dev/null | grep "Token (base64):" | cut -d' ' -f3 | base64 -d 2>/dev/null || echo "")
        
        if [[ -z "$TOKEN" ]]; then
            echo "ERROR: Could not extract token from job logs"
            exit 1
        fi
        
        echo "Found token: ${TOKEN:0:8}..."
        
        # Update 1Password using the Connect API
        echo "Updating 1Password with new token..."
        
        # Get 1Password Connect token
        CONNECT_TOKEN=$(kubectl get secret onepassword-connect-token -n onepassword-connect -o jsonpath='{.data.token}' 2>/dev/null | base64 -d || echo "")
        
        if [[ -z "$CONNECT_TOKEN" ]]; then
            echo "ERROR: Could not get 1Password Connect token"
            exit 1
        fi
        
        # Update the 1Password item
        CONNECT_URL="http://onepassword-connect.onepassword-connect.svc.cluster.local:8080"
        ITEM_ID="Authentik RADIUS Token - home-ops"
        
        # Create update payload
        cat > /tmp/update_payload.json << EOF
    {
        "fields": [
            {
                "id": "token",
                "value": "$TOKEN"
            }
        ]
    }
    EOF
        
        # Update 1Password
        RESPONSE=$(curl -s -w "%{http_code}" -o /tmp/response.json \
            -X PATCH "$CONNECT_URL/v1/vaults/homelab/items/$ITEM_ID" \
            -H "Authorization: Bearer $CONNECT_TOKEN" \
            -H "Content-Type: application/json" \
            -d @/tmp/update_payload.json)
        
        if [[ "$RESPONSE" == "200" ]]; then
            echo "✅ Successfully updated 1Password with new token"
            echo "Token rotation completed successfully!"
            exit 0
        else
            echo "❌ Failed to update 1Password (HTTP $RESPONSE)"
            cat /tmp/response.json
            exit 1
        fi
        
    elif [[ "$1" == "list" ]]; then
        echo "Listing current tokens..."
        # Simple implementation for now
        echo '[{"key":"current","days_remaining":365,"status":"active"}]'
        
    else
        echo "Usage: $0 {list|rotate}"
        exit 1
    fi