---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-monitoring
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 10m0s
  path: ./apps/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-ingress-nginx
    - name: infrastructure-longhorn
  retryInterval: 2m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dashboard
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  path: ./apps/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-ingress-nginx
  retryInterval: 1m0s
  wait: true