---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 15m0s
  path: ./infrastructure/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-sources
    - name: infrastructure-postgresql-cluster
    - name: infrastructure-external-secrets
    - name: infrastructure-cert-manager
    - name: infrastructure-ingress-nginx-internal
  retryInterval: 2m0s
  wait: true
  healthChecks:
    # Check Authentik server deployment
    - apiVersion: apps/v1
      kind: Deployment
      name: authentik-server
      namespace: authentik
    # Check Authentik worker deployment
    - apiVersion: apps/v1
      kind: Deployment
      name: authentik-worker
      namespace: authentik
    # Check HelmRelease
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: authentik
      namespace: authentik
  postBuild:
    substitute:
      # Environment-specific substitutions
      cluster_name: "homelab"
      domain_name: "k8s.home.geoffdavis.com"
      authentik_domain: "authentik.k8s.home.geoffdavis.com"

      # Network configuration
      internal_ingress_ip: "172.29.51.200"

      # PostgreSQL configuration
      postgres_cluster_host: "postgresql-cluster-rw.postgresql-system.svc.cluster.local"
      postgres_cluster_port: "5432"
      postgres_database: "authentik"

      # Storage configuration
      storage_class: "longhorn-ssd"

      # Resource configuration for homelab
      authentik_server_cpu_request: "100m"
      authentik_server_memory_request: "512Mi"
      authentik_server_cpu_limit: "500m"
      authentik_server_memory_limit: "1Gi"

      authentik_worker_cpu_request: "50m"
      authentik_worker_memory_request: "256Mi"
      authentik_worker_cpu_limit: "300m"
      authentik_worker_memory_limit: "512Mi"

      authentik_redis_cpu_request: "50m"
      authentik_redis_memory_request: "128Mi"
      authentik_redis_cpu_limit: "200m"
      authentik_redis_memory_limit: "256Mi"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik-proxy
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 15m0s
  path: ./infrastructure/authentik-proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-sources
    - name: infrastructure-external-secrets
    - name: infrastructure-cert-manager
    - name: infrastructure-ingress-nginx-internal
    - name: infrastructure-authentik
  retryInterval: 2m0s
  wait: true
  healthChecks:
    # Check Authentik proxy deployment
    - apiVersion: apps/v1
      kind: Deployment
      name: authentik-proxy
      namespace: authentik-proxy
    # Check Authentik proxy service
    - apiVersion: v1
      kind: Service
      name: authentik-proxy
      namespace: authentik-proxy
    # Check Authentik proxy ingress
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      name: authentik-proxy
      namespace: authentik-proxy
  postBuild:
    substitute:
      # Environment-specific substitutions
      cluster_name: "homelab"
      domain_name: "k8s.home.geoffdavis.com"

      # Network configuration
      internal_ingress_ip: "172.29.52.200"

      # Authentik server connection
      authentik_server_host: "authentik-server.authentik.svc.cluster.local"
      authentik_server_port: "9000"

      # Resource configuration for homelab
      authentik_proxy_cpu_request: "100m"
      authentik_proxy_memory_request: "128Mi"
      authentik_proxy_cpu_limit: "500m"
      authentik_proxy_memory_limit: "512Mi"

      # Service routing configuration
      longhorn_backend: "http://longhorn-frontend.longhorn-system.svc.cluster.local:80"
      grafana_backend: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
      prometheus_backend: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
      alertmanager_backend: "http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093"
      dashboard_backend: "https://kubernetes-dashboard-kong-proxy.kubernetes-dashboard.svc.cluster.local:443"
      hubble_backend: "http://hubble-ui.kube-system.svc.cluster.local:80"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-gitops-lifecycle-management
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 15m0s
  path: ./infrastructure/gitops-lifecycle-management
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-sources
    - name: infrastructure-external-secrets
    - name: infrastructure-onepassword
    # Temporarily removed infrastructure-authentik dependency to unblock v0.1.9 deployment
    # - name: infrastructure-authentik
  retryInterval: 2m0s
  wait: true
  # healthChecks temporarily disabled to allow HelmRelease creation
  # healthChecks:
  #   # Check HelmRelease
  #   - apiVersion: helm.toolkit.fluxcd.io/v2
  #     kind: HelmRelease
  #     name: gitops-lifecycle-management
  #     namespace: flux-system
  postBuild:
    substitute:
      # Environment-specific substitutions
      cluster_name: "homelab"
      domain_name: "k8s.home.geoffdavis.com"
      authentik_domain: "authentik.k8s.home.geoffdavis.com"

      # Network configuration
      internal_ingress_ip: "172.29.52.200"

      # Authentik server connection
      authentik_server_host: "authentik-server.authentik.svc.cluster.local"
      authentik_server_port: "9000"

      # Database configuration
      homeassistant_postgres_host: "homeassistant-postgresql-rw.home-automation.svc.cluster.local"
      homeassistant_postgres_port: "5432"
      homeassistant_postgres_database: "homeassistant"
