---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik-outpost-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-authentik
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/authentik-outpost-config
  prune: true
  wait: true
  healthChecks:
    # Check that the outpost configuration job completes successfully
    - apiVersion: batch/v1
      kind: Job
      name: authentik-radius-outpost-config
      namespace: authentik