---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik-outpost-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-authentik
    - name: infrastructure-external-secrets
    - name: infrastructure-onepassword
  interval: 30m
  retryInterval: 2m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/authentik-outpost-config
  prune: true
  wait: true
  healthChecks:
    # Check that the enhanced token setup job completes successfully
    - apiVersion: batch/v1
      kind: Job
      name: authentik-enhanced-token-setup
      namespace: authentik
    # Check that the OIDC setup jobs complete successfully
    - apiVersion: batch/v1
      kind: Job
      name: grafana-oidc-setup
      namespace: authentik
    - apiVersion: batch/v1
      kind: Job
      name: dashboard-oidc-setup
      namespace: authentik
    # Check that the outpost configuration job completes successfully
    - apiVersion: batch/v1
      kind: Job
      name: authentik-radius-outpost-config
      namespace: authentik
