---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik-outpost-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-authentik
    - name: infrastructure-external-secrets
    - name: infrastructure-onepassword-connect
    - name: infrastructure-gitops-lifecycle-management
  interval: 30m
  retryInterval: 2m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/authentik-outpost-config
  prune: true
  wait: true
  healthChecks:
    # Check that the RADIUS outpost configuration job completes successfully
    # (Other jobs are now handled by GitOps Lifecycle Management chart)
    - apiVersion: batch/v1
      kind: Job
      name: authentik-radius-outpost-config
      namespace: authentik
