---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik-radius
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-authentik
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/authentik-radius
  prune: true
  wait: true