apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-cluster-backup
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: postgresql-cluster
    app.kubernetes.io/component: database
    backup-tier: "critical"
    backup-type: "database"
spec:
  # Schedule backups daily at 3 AM
  schedule: "0 3 * * *"

  # Backup retention policy
  backupOwnerReference: self

  # Target cluster
  cluster:
    name: postgresql-cluster

  # Backup method and configuration - using plugin
  method: plugin
  pluginConfiguration:
    name: "barman-cloud.cloudnative-pg.io"
    parameters:
      objectStoreName: "postgresql-cluster-backup"

  # Immediate checkpoint for consistent backup (handled automatically by plugin)

  # Suspend backup if needed
  suspend: false

---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgresql-cluster-bootstrap-backup
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: postgresql-cluster
    app.kubernetes.io/component: database
    backup-tier: "critical"
    backup-type: "database"
    backup-purpose: "bootstrap"
spec:
  # Target cluster
  cluster:
    name: postgresql-cluster

  # Backup method - using plugin
  method: plugin
  pluginConfiguration:
    name: "barman-cloud.cloudnative-pg.io"
    parameters:
      objectStoreName: "postgresql-cluster-backup"

  # Immediate checkpoint for consistent backup (handled automatically by plugin)
