apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: postgresql-cluster
    app.kubernetes.io/component: database
spec:
  # High availability configuration - 3 replicas for homelab
  instances: 3

  # PostgreSQL version and image
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  # Primary update strategy
  primaryUpdateStrategy: unsupervised

  # PostgreSQL configuration
  postgresql:
    parameters:
      # Performance tuning for homelab
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

      # Logging configuration
      log_statement: "none"
      log_min_duration_statement: "1000"
      log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "

      # Replication settings
      max_wal_senders: "10"
      max_replication_slots: "10"
      wal_level: "replica"

      # Archive settings for backup
      archive_mode: "on"
      archive_timeout: "5min"

  # Bootstrap configuration
  bootstrap:
    initdb:
      database: "app"
      owner: "app"
      secret:
        name: postgresql-superuser-credentials
      dataChecksums: true
      encoding: "UTF8"
      localeCType: "C"
      localeCollate: "C"

  # Storage configuration with Longhorn
  storage:
    size: 20Gi
    storageClass: longhorn-ssd

  # Resource limits appropriate for homelab
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  # Superuser secret and access
  superuserSecret:
    name: postgresql-superuser-credentials
  enableSuperuserAccess: true
