apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-s3-backup-credentials
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: postgresql-cluster
    app.kubernetes.io/component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: postgresql-s3-backup-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_S3_ENDPOINT: "https://s3.amazonaws.com"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "AWS Access Key - longhorn-s3-backup - home-ops"
        property: "access key id"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "AWS Access Key - longhorn-s3-backup - home-ops"
        property: "secret access key"