---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-database-credentials
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: postgresql-cluster
    app.kubernetes.io/component: database
    application: homeassistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: homeassistant-database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: postgresql-cluster
          app.kubernetes.io/component: database
          application: homeassistant
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        database: "homeassistant"
        host: "postgresql-cluster-rw.postgresql-system.svc.cluster.local"
        port: "5432"
        # Full connection string
        connection_string: "postgresql://{{ .username }}:{{ .password }}@postgresql-cluster-rw.postgresql-system.svc.cluster.local:5432/homeassistant"
  data:
    - secretKey: username
      remoteRef:
        key: "Home Assistant Database - home-ops"
        property: "username"
    - secretKey: password
      remoteRef:
        key: "Home Assistant Database - home-ops"
        property: "password"