apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster.yaml
  - external-secret-superuser.yaml
  - external-secret-s3-backup.yaml
  - backup-configuration.yaml
  - monitoring.yaml
  - recurring-job-database.yaml

# Common labels for all PostgreSQL cluster resources
commonLabels:
  app.kubernetes.io/name: postgresql-cluster
  app.kubernetes.io/component: database
  backup-tier: "critical"
  backup-type: "database"
  application: "postgresql"

# Namespace for all resources
namespace: postgresql-system
