apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.14.5"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 12h
  values:
    # Configure multiple providers
    provider: cloudflare
    
    # Cloudflare configuration
    cloudflare:
      apiToken: ""
      secretName: cloudflare-api-token
      
    # Domain configuration - fits with existing home domain structure
    domainFilters:
      - geoffdavis.com
      - k8s.home.geoffdavis.com
      
    # Zone ID filters (optional)
    zoneIdFilters: []
    
    # Policy configuration
    policy: sync
    
    # Registry configuration
    registry: txt
    txtOwnerId: "home-ops"
    txtPrefix: "external-dns-"
    
    # Deployment configuration
    replicas: 1
    
    # Resource limits
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 25Mi
        
    # Node selector and tolerations
    nodeSelector:
      kubernetes.io/os: linux
      
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
        
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      
    # Pod security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      
    # Service configuration
    service:
      enabled: true
      type: ClusterIP
      
    # ServiceAccount configuration
    serviceAccount:
      create: true
      name: external-dns
      
    # RBAC configuration
    rbac:
      create: true
      
    # Metrics configuration
    metrics:
      enabled: true
      port: 7979
      
    # Logging configuration
    logLevel: info
    logFormat: text
    
    # Interval configuration
    interval: 1m
    
    # Source configuration
    sources:
      - service
      - ingress
      - crd
      
    # Annotation filters
    annotationFilter: "external-dns.alpha.kubernetes.io/hostname"
    
    # Extra arguments
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --cloudflare-proxied
      - --cloudflare-dns-records-per-page=5000
      
    # Environment variables
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
            
    # Probes configuration
    livenessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 2
      successThreshold: 1
      
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
      
    # Pod disruption budget
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
      
    # Priority class
    priorityClassName: ""
    
    # Pod annotations
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "7979"
      prometheus.io/path: "/metrics"
      
    # Deployment annotations
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
      
    # Pod labels
    podLabels:
      app.kubernetes.io/component: dns-controller
      
    # Configure monitoring
    serviceMonitor:
      enabled: true
      namespace: external-dns-system
      interval: 30s
      scrapeTimeout: 10s
      
    # Configure dry-run mode (set to false for production)
    dryRun: false
    
    # Configure trigger loop on events
    triggerLoopOnEvent: false
    
    # Configure batch change size
    batchChangeSize: 1000
    
    # Configure batch change interval
    batchChangeInterval: 1s