apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  timeout: 30m
  install:
    timeout: 30m
    remediation:
      retries: 3
  upgrade:
    timeout: 30m
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 20m
    cleanupOnFail: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.15.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  values:
    alertmanager:
      enabled: true
      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-pool: "bgp-default"

    prometheus:
      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-pool: "bgp-default"

      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            metadata:
              labels:
                backup-tier: "critical"
                backup-group: "monitoring"
                app: "prometheus"
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi

        nodeSelector:
          kubernetes.io/os: linux

        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule

    grafana:
      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-pool: "bgp-default"

      persistence:
        enabled: true
        storageClassName: longhorn
        size: 10Gi
        annotations:
          backup-tier: "critical"
          backup-group: "monitoring"
          app: "grafana"

      # Fix pod security policy violations
      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
        seccompProfile:
          type: RuntimeDefault

      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 472
        runAsGroup: 472
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

      # Disable the problematic init container and use fsGroup instead
      initChownData:
        enabled: false

      nodeSelector:
        kubernetes.io/os: linux

      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
