apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cnpg-monitoring
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - service-monitor.yaml
  - prometheus-rules.yaml
  - grafana-dashboard.yaml
  - health-check-cronjob.yaml
  - rbac.yaml

commonLabels:
  app.kubernetes.io/name: cnpg-monitoring
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: cnpg-barman-plugin

# Patch components to use the cnpg-monitoring namespace
patchesStrategicMerge:
  - |-
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: cnpg-barman-plugin
      namespace: cnpg-monitoring
    spec:
      selector:
        matchLabels:
          cnpg.io/cluster: ""
      namespaceSelector:
        matchNames:
          - home-automation
          - postgresql-system
          - cnpg-system

  - |-
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: cnpg-objectstore
      namespace: cnpg-monitoring
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: objectstore-controller
      namespaceSelector:
        matchNames:
          - home-automation
          - postgresql-system

  - |-
    apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: cnpg-barman-plugin-alerts
      namespace: cnpg-monitoring
      labels:
        prometheus: kube-prometheus
        role: alert-rules

  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cnpg-barman-plugin-dashboard
      namespace: cnpg-monitoring
      labels:
        grafana_dashboard: "1"

# Configuration for automated health checks
configMapGenerator:
  - name: cnpg-health-check-config
    files:
      - scripts/health-check.sh=../../scripts/cnpg-monitoring/health-check.sh
      - scripts/backup-restore-test.sh=../../scripts/cnpg-monitoring/backup-restore-test.sh
      - scripts/performance-monitor.sh=../../scripts/cnpg-monitoring/performance-monitor.sh
    options:
      disableNameSuffixHash: true
