apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cnpg-monitoring
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - service-monitor.yaml
  - prometheus-rules.yaml
  - grafana-dashboard.yaml
  - health-check-cronjob.yaml
  - rbac.yaml

commonLabels:
  app.kubernetes.io/name: cnpg-monitoring
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: cnpg-barman-plugin

# Namespace is set correctly in base files, no patches needed

# Configuration for automated health checks
configMapGenerator:
  - name: cnpg-health-check-config
    files:
      - scripts/health-check.sh=../../scripts/cnpg-monitoring/health-check.sh
      - scripts/backup-restore-test.sh=../../scripts/cnpg-monitoring/backup-restore-test.sh
      - scripts/performance-monitor.sh=../../scripts/cnpg-monitoring/performance-monitor.sh
    options:
      disableNameSuffixHash: true
