apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg-system
spec:
  interval: 30m
  timeout: 15m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: true
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 12h
  values:
    # Operator configuration
    fullnameOverride: cnpg-operator

    # Replica configuration for homelab
    replicaCount: 1

    # Image configuration
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      pullPolicy: IfNotPresent

    # Resource limits appropriate for homelab
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi

    # Node selector and tolerations
    nodeSelector:
      kubernetes.io/os: linux

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    # Pod security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      seccompProfile:
        type: RuntimeDefault

    # Service account configuration
    serviceAccount:
      create: true
      name: cnpg-operator

    # RBAC configuration
    rbac:
      create: true

    # Webhook configuration
    webhook:
      enabled: true
      port: 9443
      mutating:
        create: true
        failurePolicy: Fail
      validating:
        create: true
        failurePolicy: Fail

    # Monitoring configuration
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
        namespace: cnpg-system
        interval: 30s
        scrapeTimeout: 10s

    # Metrics configuration
    metrics:
      enabled: true
      port: 8080

    # Pod annotations for monitoring
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"

    # Deployment annotations
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"

    # Pod labels
    podLabels:
      app.kubernetes.io/component: operator

    # Logging configuration
    logLevel: info

    # Leader election configuration
    leaderElection:
      enabled: true

    # Pod disruption budget
    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    # Affinity configuration for homelab
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - cloudnative-pg
              topologyKey: kubernetes.io/hostname

    # Configure operator scope (cluster-wide)
    watchNamespace: ""

    # Configure CRD management
    crds:
      create: true
