apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cnpg-webhook-cert
  namespace: cnpg-system
spec:
  secretName: cnpg-webhook-cert
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - cnpg-webhook-service
    - cnpg-webhook-service.cnpg-system
    - cnpg-webhook-service.cnpg-system.svc
    - cnpg-webhook-service.cnpg-system.svc.cluster.local