apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: authentik-outpost-config
  namespace: authentik

resources:
  # Outpost configuration job
  - outpost-config-job.yaml

labels:
  - pairs:
      app.kubernetes.io/name: authentik-outpost-config
      app.kubernetes.io/part-of: identity-provider
      app.kubernetes.io/component: configuration

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: authentik-outpost-config
    app.kubernetes.io/component: configuration
  annotations:
    config.kubernetes.io/local-config: "true"