apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: authentik-outpost-config
  namespace: authentik

resources:
  # RBAC configuration (must be first)
  - rbac.yaml
  # RADIUS outpost configuration (specialized, not replaced by GitOps Lifecycle Management)
  - radius-outpost-config-job.yaml
  
  # NOTE: The following jobs are now replaced by the GitOps Lifecycle Management Helm chart:
  # - enhanced-token-setup-job.yaml (replaced by chart's authentication hooks)
  # - grafana-oidc-setup-job.yaml (replaced by chart's OIDC setup)
  # - dashboard-oidc-setup-job.yaml (replaced by chart's OIDC setup)
  # - cleanup-duplicate-tokens-job.yaml (replaced by chart's cleanup policies)
  
  # NOTE: ALL embedded outpost jobs disabled for external outpost architecture
  # The external outpost handles all proxy providers via authentik-proxy namespace
  # - embedded-outpost-config-job.yaml
  # DISABLED: These create competing "proxy-outpost" that conflicts with external outpost
  # - longhorn-proxy-config-job.yaml
  # - dashboard-proxy-config-job.yaml
  # - hubble-proxy-config-job.yaml
  # - monitoring-proxy-config-job.yaml

labels:
  - pairs:
      app.kubernetes.io/name: authentik-outpost-config
      app.kubernetes.io/part-of: identity-provider
      app.kubernetes.io/component: configuration

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: authentik-outpost-config
    app.kubernetes.io/component: configuration
  annotations:
    config.kubernetes.io/local-config: "true"
