apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

metadata:
  name: authentik-outpost-config
  namespace: authentik

resources:
  # Enhanced admin token setup with 1-year expiry (runs first)
  - enhanced-token-setup-job.yaml
  # Outpost configuration jobs (run after token setup)
  # NOTE: ALL embedded outpost jobs disabled for external outpost architecture
  # The external outpost handles all proxy providers via authentik-proxy namespace
  # - embedded-outpost-config-job.yaml
  - radius-outpost-config-job.yaml
  # DISABLED: These create competing "proxy-outpost" that conflicts with external outpost
  # - longhorn-proxy-config-job.yaml
  # - dashboard-proxy-config-job.yaml
  # - hubble-proxy-config-job.yaml
  # - monitoring-proxy-config-job.yaml

labels:
  - pairs:
      app.kubernetes.io/name: authentik-outpost-config
      app.kubernetes.io/part-of: identity-provider
      app.kubernetes.io/component: configuration

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: authentik-outpost-config
    app.kubernetes.io/component: configuration
  annotations:
    config.kubernetes.io/local-config: "true"
