apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-admin-token
  namespace: authentik-proxy
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/part-of: identity-provider
    app.kubernetes.io/component: external-outpost
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-admin-token
    creationPolicy: Owner
  data:
    - secretKey: token # pragma: allowlist secret
      remoteRef:
        key: authentik-admin-api-token
        property: credential
