apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-external-outpost-token
  namespace: authentik-proxy
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/part-of: identity-provider
    app.kubernetes.io/component: external-outpost
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-external-outpost-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        token: "{{ .token }}"
        authentik_host: "http://authentik-server.authentik.svc.cluster.local:80"
        authentik_insecure: "false"
  data:
    - secretKey: token
      remoteRef:
        key: "Authentik External Outpost Token - home-ops"
        property: "token"
