apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-proxy
  namespace: authentik-proxy
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/part-of: identity-provider
    app.kubernetes.io/component: external-outpost
  annotations:
    # Use internal ingress controller with BGP load balancer
    kubernetes.io/ingress.class: nginx-internal

    # TLS configuration
    cert-manager.io/cluster-issuer: selfsigned-issuer

    # Nginx configuration for proxy functionality
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    # Proxy configuration for Authentik outpost
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

    # External DNS configuration - let external-dns-internal handle this ingress
    # Remove controller annotation since external-dns doesn't support --controller-name flag
    external-dns.alpha.kubernetes.io/hostname: "longhorn.k8s.home.geoffdavis.com,grafana.k8s.home.geoffdavis.com,alertmanager.k8s.home.geoffdavis.com,dashboard.k8s.home.geoffdavis.com,hubble.k8s.home.geoffdavis.com,homeassistant.k8s.home.geoffdavis.com"
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
        - longhorn.k8s.home.geoffdavis.com
        - grafana.k8s.home.geoffdavis.com
        - alertmanager.k8s.home.geoffdavis.com
        - dashboard.k8s.home.geoffdavis.com
        - hubble.k8s.home.geoffdavis.com
        - homeassistant.k8s.home.geoffdavis.com
      secretName: authentik-proxy-tls
  rules:
    # Longhorn Storage Management
    - host: longhorn.k8s.home.geoffdavis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-proxy
                port:
                  number: 9000

    # Grafana Monitoring Dashboard
    - host: grafana.k8s.home.geoffdavis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-proxy
                port:
                  number: 9000

    # AlertManager Alert Routing
    - host: alertmanager.k8s.home.geoffdavis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-proxy
                port:
                  number: 9000

    # Kubernetes Dashboard
    - host: dashboard.k8s.home.geoffdavis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-proxy
                port:
                  number: 9000

    # Hubble Network Observability
    - host: hubble.k8s.home.geoffdavis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-proxy
                port:
                  number: 9000

    # Home Assistant Home Automation
    - host: homeassistant.k8s.home.geoffdavis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-proxy
                port:
                  number: 9000
