apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: authentik-proxy
  namespace: authentik-proxy

resources:
  # Core namespace and RBAC
  - namespace.yaml
  - rbac.yaml

  # Configuration and secrets
  - configmap.yaml
  - secret.yaml
  - external-outpost-secret.yaml
  - admin-token-secret.yaml
  - database-credentials-secret.yaml
  - outpost-id-static.yaml
  - service-discovery-config.yaml

  # Redis for session storage
  - redis.yaml

  # Application deployment
  - deployment.yaml
  - service.yaml
  - ingress.yaml

  # Configuration approaches (choose one):

  # Option 1: Helm-based configuration (centralized) - PREFERRED for GitOps reliability
  - helmrelease-config.yaml

  # Option 2: Simplified static configuration (replaces complex CronJob) - DISABLED: Jobs can fail and block GitOps
  # - static-proxy-config.yaml

  # Authentication flow testing (temporarily disabled)
  # - test-authentication-flow.yaml

  # Legacy configuration jobs (removed after migration to static ConfigMaps)
  # - proxy-config-job-simple.yaml (converted to outpost-id-static.yaml)
  # - fix-dashboard-kong-service-job.yaml

commonLabels:
  app.kubernetes.io/name: authentik-proxy
  app.kubernetes.io/part-of: identity-provider
  app.kubernetes.io/component: external-outpost

images:
  - name: ghcr.io/goauthentik/proxy
    newTag: "2025.8.4"

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/component: external-outpost
  annotations:
    config.kubernetes.io/local-config: "true"

# Namespace for all resources
namespace: authentik-proxy

# Configuration patches
patches:
  # Ensure proper resource limits based on cluster capacity
  - target:
      kind: Deployment
      name: authentik-proxy
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"

# Replica configuration for high availability
replicas:
  - name: authentik-proxy
    count: 2
