apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-proxy-outpost-id
  namespace: authentik-proxy
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/component: configuration
data:
  outpost_id: "3f0970c5-d6a3-43b2-9a36-d74665c6b24e"
