apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-proxy-outpost-id
  namespace: authentik-proxy
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/part-of: identity-provider
    app.kubernetes.io/component: external-outpost
data:
  # External outpost ID (k8s-external-proxy-outpost)
  # This outpost handles 6 services: longhorn, grafana, prometheus, alertmanager, hubble, homeassistant
  # Dashboard is now internal-only and bypasses the proxy
  outpost_id: "26d1a2cc-cdc3-42b1-84a0-9f3dbc6b6083"
