apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-proxy-outpost-id
  namespace: authentik-proxy
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/part-of: identity-provider
    app.kubernetes.io/component: external-outpost
data:
  # External outpost ID (k8s-external-proxy-outpost)
  # This outpost handles 5 services: longhorn, grafana, prometheus, alertmanager, hubble
  # Dashboard is now internal-only and bypasses the proxy
  outpost_id: "3f0970c5-d6a3-43b2-9a36-d74665c6b24e"
