apiVersion: batch/v1
kind: Job
metadata:
  name: authentik-proxy-config-simple
  namespace: authentik-proxy
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-weight: "20"
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/part-of: identity-provider
    app.kubernetes.io/component: configuration
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik-proxy-config
        app.kubernetes.io/component: configuration
    spec:
      restartPolicy: OnFailure
      serviceAccountName: authentik-proxy
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: update-configmap
          image: bitnami/kubectl:1.31.1
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "=== Updating ConfigMap with Known Outpost ID ==="

              # Use the known external outpost ID
              OUTPOST_ID="3f0970c5-d6a3-43b2-9a36-d74665c6b24e"
              echo "Using outpost ID: $OUTPOST_ID"

              # Update ConfigMap with outpost ID
              cat <<EOF | kubectl apply -f -
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: authentik-proxy-outpost-id
                namespace: authentik-proxy
                labels:
                  app.kubernetes.io/name: authentik-proxy
                  app.kubernetes.io/component: configuration
              data:
                outpost_id: "$OUTPOST_ID"
              EOF

              echo "✓ ConfigMap updated with outpost ID: $OUTPOST_ID"
              echo "=== Simple Configuration Job Complete ==="
              echo "✓ External URL fixes have been applied via:"
              echo "  - Environment variables (secret.yaml)"
              echo "  - ConfigMap configuration (configmap.yaml)"
              echo "  - Known external outpost ID: $OUTPOST_ID"
