apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-proxy-token
  namespace: authentik-proxy
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/part-of: identity-provider
    app.kubernetes.io/component: external-outpost
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: authentik-proxy-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        token: "{{ .token }}"
        authentik_host: "https://authentik.k8s.home.geoffdavis.com"
        authentik_insecure: "false"
  data:
    - secretKey: token
      remoteRef:
        key: "Authentik Admin API Token - home-ops"
        property: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-proxy-config
  namespace: authentik-proxy
  labels:
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/part-of: identity-provider
    app.kubernetes.io/component: external-outpost
type: Opaque
stringData:
  # Authentik proxy configuration
  AUTHENTIK_HOST: "https://authentik.k8s.home.geoffdavis.com"
  AUTHENTIK_INSECURE: "false"
  AUTHENTIK_LOG_LEVEL: "info"
  # Will be populated by ExternalSecret
  AUTHENTIK_TOKEN: ""