{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: proxyconfigs.gitops.io
  labels:
    {{- include "gitops-lifecycle-management.labels" . | nindent 4 }}
  annotations:
    {{- include "gitops-lifecycle-management.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  group: gitops.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              serviceName:
                type: string
                description: "Name of the Kubernetes service"
              serviceNamespace:
                type: string
                description: "Namespace of the Kubernetes service"
              externalHost:
                type: string
                description: "External hostname for the proxy provider"
              internalHost:
                type: string
                description: "Internal service URL"
              port:
                type: integer
                description: "Service port"
                default: 80
              protocol:
                type: string
                description: "Service protocol"
                default: "http"
                enum: ["http", "https"]
              authentikConfig:
                type: object
                properties:
                  enabled:
                    type: boolean
                    description: "Enable Authentik proxy provider creation"
                    default: true
                  providerName:
                    type: string
                    description: "Name for the Authentik proxy provider"
                  mode:
                    type: string
                    description: "Authentik proxy mode"
                    default: "forward_single"
                    enum: ["forward_single", "forward_domain", "proxy"]
                  skipPathRegex:
                    type: string
                    description: "Regex for paths to skip authentication"
                    default: "^/api/.*$"
                  basicAuthEnabled:
                    type: boolean
                    description: "Enable basic authentication"
                    default: false
                  internalHostSslValidation:
                    type: boolean
                    description: "Validate SSL for internal host"
                    default: false
                required:
                - providerName
              labels:
                type: object
                additionalProperties:
                  type: string
                description: "Additional labels for the proxy configuration"
              annotations:
                type: object
                additionalProperties:
                  type: string
                description: "Additional annotations for the proxy configuration"
            required:
            - serviceName
            - serviceNamespace
            - externalHost
            - internalHost
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
                  required:
                  - type
                  - status
              authentikProviderId:
                type: string
                description: "ID of the created Authentik proxy provider"
              lastReconciled:
                type: string
                format: date-time
                description: "Last time the configuration was reconciled"
              phase:
                type: string
                description: "Current phase of the proxy configuration"
                enum: ["Pending", "Ready", "Failed"]
    additionalPrinterColumns:
    - name: Service
      type: string
      description: "Target service"
      jsonPath: .spec.serviceName
    - name: Namespace
      type: string
      description: "Service namespace"
      jsonPath: .spec.serviceNamespace
    - name: External Host
      type: string
      description: "External hostname"
      jsonPath: .spec.externalHost
    - name: Phase
      type: string
      description: "Configuration phase"
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: proxyconfigs
    singular: proxyconfig
    kind: ProxyConfig
    shortNames:
    - pc
{{- end }}