---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: home-automation
  namespace: home-automation

resources:
  - namespace.yaml
  - home-assistant/
  - mosquitto/
  - redis/
  - matter-server/
  - backup-config.yaml

labels:
  - pairs:
      app.kubernetes.io/name: home-automation
      app.kubernetes.io/part-of: home-automation-stack

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: home-automation
    app.kubernetes.io/part-of: home-automation-stack
  annotations:
    config.kubernetes.io/local-config: "true"
