apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Phase 1: LoadBalancer IP Pools
  # These deploy early to be ready for services that need LoadBalancer IPs
  - loadbalancer-pools.yaml
