apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeassistant-postgresql
  namespace: home-automation
  labels:
    app.kubernetes.io/name: homeassistant-postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: home-automation-stack
    backup-tier: "important"
    backup-type: "database"
    application: "homeassistant"
spec:
  # Single instance for Home Assistant (can be scaled later)
  instances: 1

  # PostgreSQL version and image
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  # Primary update strategy
  primaryUpdateStrategy: unsupervised

  # PostgreSQL configuration optimized for Home Assistant
  postgresql:
    parameters:
      # Performance tuning for Home Assistant workload
      max_connections: "100"
      shared_buffers: "128MB"
      effective_cache_size: "512MB"
      maintenance_work_mem: "32MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "8MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "2MB"
      min_wal_size: "512MB"
      max_wal_size: "2GB"

      # Logging configuration (log_destination managed by CloudNativePG)
      log_statement: "none"
      log_min_duration_statement: "2000"
      log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "

      # Connection and authentication (SSL managed by CloudNativePG)
      # SSL configuration is handled automatically by CloudNativePG

      # Replication settings
      max_wal_senders: "5"
      max_replication_slots: "5"
      wal_level: "replica"
      # hot_standby managed by CloudNativePG

      # Archive settings for backup
      archive_mode: "on"
      archive_timeout: "10min"

  # Bootstrap configuration
  bootstrap:
    initdb:
      database: "homeassistant"
      owner: "homeassistant"
      secret:
        name: homeassistant-postgresql-superuser
      dataChecksums: true
      encoding: "UTF8"
      localeCType: "C"
      localeCollate: "C"

  # Storage configuration with Longhorn
  storage:
    size: 10Gi
    storageClass: longhorn-ssd

  # Resource limits appropriate for Home Assistant
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  # Plugin configuration for Barman Cloud backup
  plugins:
    - name: "barman-cloud.cloudnative-pg.io"
      enabled: true
      isWALArchiver: true
      parameters:
        objectStoreName: "homeassistant-postgresql-backup"

  # Certificates configuration - CloudNativePG manages TLS automatically
  # No explicit certificate configuration needed

  # Superuser secret
  superuserSecret:
    name: homeassistant-postgresql-superuser
  enableSuperuserAccess: true
