apiVersion: batch/v1
kind: Job
metadata:
  name: homeassistant-database-init
  namespace: home-automation
  labels:
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/component: database-init
    app.kubernetes.io/part-of: home-automation-stack
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-1"
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homeassistant
        app.kubernetes.io/component: database-init
        app.kubernetes.io/part-of: home-automation-stack
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: database-init
          image: postgres:17.5-alpine
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: PGHOST
              value: "homeassistant-postgresql-rw.home-automation.svc.cluster.local"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "postgres"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: homeassistant-postgresql-superuser
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: homeassistant-postgresql-superuser
                  key: password
            - name: APP_DB_USER
              valueFrom:
                secretKeyRef:
                  name: homeassistant-database-credentials
                  key: username
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homeassistant-database-credentials
                  key: password
            - name: PGSSLMODE
              value: "require"
            - name: TARGET_DATABASE
              value: "homeassistant"
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Initializing database: ${TARGET_DATABASE} for Home Assistant"
              echo "Connecting to PostgreSQL cluster..."

              # Function to execute SQL with retry
              execute_sql() {
                local sql="$1"
                local max_attempts=5
                local attempt=1

                while [ $attempt -le $max_attempts ]; do
                  echo "Attempt $attempt: $sql"
                  if psql -c "$sql"; then
                    echo "Success!"
                    return 0
                  else
                    echo "Failed, retrying in 5 seconds..."
                    sleep 5
                    attempt=$((attempt + 1))
                  fi
                done

                echo "Failed after $max_attempts attempts"
                return 1
              }

              # Check if database exists
              DB_EXISTS=$(psql -tAc "SELECT 1 FROM pg_database WHERE datname='${TARGET_DATABASE}';" || echo "0")

              if [ "$DB_EXISTS" != "1" ]; then
                echo "Creating ${TARGET_DATABASE} database..."
                execute_sql "CREATE DATABASE ${TARGET_DATABASE} OWNER ${APP_DB_USER};"
                echo "Database created successfully"
              else
                echo "Database ${TARGET_DATABASE} already exists"
              fi

              # Check if user exists
              USER_EXISTS=$(psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${APP_DB_USER}';" || echo "0")

              if [ "$USER_EXISTS" != "1" ]; then
                echo "Creating ${APP_DB_USER} user..."
                execute_sql "CREATE USER ${APP_DB_USER} WITH PASSWORD '${APP_DB_PASSWORD}';"
                echo "User created successfully"
              else
                echo "User ${APP_DB_USER} already exists"
                echo "Updating password..."
                execute_sql "ALTER USER ${APP_DB_USER} WITH PASSWORD '${APP_DB_PASSWORD}';"
              fi

              # Grant permissions
              echo "Granting permissions..."
              execute_sql "GRANT ALL PRIVILEGES ON DATABASE ${TARGET_DATABASE} TO ${APP_DB_USER};"
              execute_sql "GRANT ${APP_DB_USER} TO postgres;"

              # Connect to the target database and grant schema permissions
              echo "Granting schema permissions..."
              PGDATABASE=${TARGET_DATABASE} psql -c "GRANT ALL ON SCHEMA public TO ${APP_DB_USER};" || true
              PGDATABASE=${TARGET_DATABASE} psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${APP_DB_USER};" || true
              PGDATABASE=${TARGET_DATABASE} psql -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${APP_DB_USER};" || true
              PGDATABASE=${TARGET_DATABASE} psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${APP_DB_USER};" || true
              PGDATABASE=${TARGET_DATABASE} psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${APP_DB_USER};" || true

              echo "Database initialization completed successfully for Home Assistant"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: tmp
          emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
