apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-postgresql-s3-backup
  namespace: home-automation
  labels:
    app.kubernetes.io/name: homeassistant-postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: home-automation-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: homeassistant-postgresql-s3-backup
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_S3_ENDPOINT: "https://s3.amazonaws.com"
  data:
    - secretKey: AWS_ACCESS_KEY_ID # pragma: allowlist secret
      remoteRef:
        key: "AWS Access Key - longhorn-s3-backup - home-ops"
        property: "access key id"
    - secretKey: AWS_SECRET_ACCESS_KEY # pragma: allowlist secret
      remoteRef:
        key: "AWS Access Key - longhorn-s3-backup - home-ops"
        property: "secret access key" # pragma: allowlist secret
