apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-postgresql-superuser
  namespace: home-automation
  labels:
    app.kubernetes.io/name: homeassistant-postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: home-automation-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: homeassistant-postgresql-superuser
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username # pragma: allowlist secret
      remoteRef:
        key: "PostgreSQL Superuser - home-ops"
        property: "username"
    - secretKey: password # pragma: allowlist secret
      remoteRef:
        key: "PostgreSQL Superuser - home-ops"
        property: "password"
