apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-database-credentials
  namespace: home-automation
  labels:
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: home-automation-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: homeassistant-database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        # Home Assistant specific database connection format
        database_url: "postgresql://{{ .username }}:{{ .password }}@homeassistant-postgresql-rw.home-automation.svc.cluster.local:5432/homeassistant"
  data:
    - secretKey: username # pragma: allowlist secret # pragma: allowlist secret
      remoteRef:
        key: "Home Assistant Database - home-ops"
        property: "username"
    - secretKey: password # pragma: allowlist secret
      remoteRef:
        key: "Home Assistant Database - home-ops"
        property: "password"
