apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: homeassistant-postgresql-backup
  namespace: home-automation
spec:
  configuration:
    destinationPath: "s3://home-assistant-postgres-backup-home-ops/homeassistant-postgresql"
    s3Credentials:
      accessKeyId:
        name: homeassistant-postgresql-s3-backup
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: homeassistant-postgresql-s3-backup
        key: AWS_SECRET_ACCESS_KEY
    wal:
      maxParallel: 2
      compression: gzip
    data:
      immediateCheckpoint: true
      jobs: 2
      compression: gzip
    tags:
      environment: "homelab"
      cluster: "homeassistant-postgresql"
      backup-tier: "important"
      application: "homeassistant"
