---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: redis
  namespace: home-automation

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: cache
      app.kubernetes.io/part-of: home-automation-stack

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
