---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: home-automation
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: home-automation-stack
    backup-tier: "important"
    backup-type: "cache"
    application: "redis"
  annotations:
    backup.longhorn.io/volume-snapshot-class: "longhorn-snapshot-vsc"
    backup.longhorn.io/recurring-job-group: "redis-cache"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 1Gi
