apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: "http://onepassword-connect.onepassword-connect.svc.cluster.local:8080"
      vaults:
        Automation: 1
        Shared: 2
      auth:
        secretRef:
          connectToken:
            name: onepassword-connect-auth
            key: token
            namespace: onepassword-connect
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword-connect
  namespace: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: "http://onepassword-connect.onepassword-connect.svc.cluster.local:8080"
      vaults:
        Automation: 1
        Shared: 2
      auth:
        secretRef:
          connectToken:
            name: onepassword-connect-auth
            key: token