apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    onepassword:
      connectHost: "http://onepassword-connect.onepassword-connect.svc.cluster.local:8080"
      vaults:
        Automation: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: onepassword-connect
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword-connect
  namespace: onepassword-connect
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    onepassword:
      connectHost: "http://onepassword-connect.onepassword-connect.svc.cluster.local:8080"
      vaults:
        Automation: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token