apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: onepassword-connect
  labels:
    app: onepassword-connect
spec:
  selector:
    app: onepassword-connect
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect-sync
  namespace: onepassword-connect
  labels:
    app: onepassword-connect
spec:
  selector:
    app: onepassword-connect
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
